### PR TITLE
feat: add feature of custom separator

### PR DESCRIPTION
**Pull request by liby**
## Changes

1. Add feature of custom separator
2. Add case conversion feature

### CODE REVIEW

**Comment by Stebalien** [comment]
Thanks for taking the time, but, unfortunately, I cannot accept this change. It's a significantly breaking change, makes the API significantly less ergonomic, and is trivial to implement by wrapping `slugify` in a new function that up-cases and replaces all dashes with underscores.

**Comment by liby** [comment]
> Thanks for taking the time

You're welcome, because I implemented these two features in my own project and opened this PR to give back to the upstream repository by the way.

> makes the API significantly less ergonomic

What kind of API design is ergonomic? Maybe this will help me improve my coding habits.

> and is trivial to implement by wrapping slugify in a new function that up-cases and replaces all dashes with underscores.

Tried, but performance is a little worse.

**Comment by Stebalien** [comment]
> What kind of API design is ergonomic? Maybe this will help me improve my coding habits.

Optimize for the common case. It's impossible to provide _every_ feature a user might want, so don't try.

In this case, `slugify("some string")` is simple and it's what users _usually_ want. `slugify("some string", '-', Some(slug::Case::Lower))` makes the user type quite a bit more, and _most_ users won't need to make these changes. 

Furthermore, it doesn't (and can't) cover all possible cases (camel case, no separators, prefix, suffix, character exclusion, etc.). In cases like this, it's usually better to just not implement a feature rather than try to cover all possible use-cases.

> Tried, but performance is a little worse.

But the question is: is this your bottleneck? If not, it doesn't really matter.

**Comment by liby** [comment]
> Optimize for the common case. It's impossible to provide every feature a user might want, so don't try.

I thought you were going to give me some advice on programming paradigms, but it doesn't look like it. I think you're talking about a matter of personal preference, which can't be called "ergonomics".


> and most users won't need to make these changes.

I'm not sure where this conclusion comes from.

In fact, most `slug` come with these features, so I'm just picking out a few here and re-implementing them. Only we disagree on this, you think users don't need them. It seems that this reason has nothing to do with ergonomics. 


> But the question is: is this your bottleneck? If not, it doesn't really matter.

It's not easy to implement case conversion by wrapping `slugify`. It is worth mentioning that in this PR, it is possible to pass `None` to indicate that no conversion is done, for example: input `HeLlo wOrLd` to get `HeLlo-wOrLd`.

How would you implement it through secondary wrapping?

**Comment by Stebalien** [comment]
> I thought you were going to give me some advice on programming paradigms, but it doesn't look like it. I think you're talking about a matter of personal preference, which can't be called "ergonomics".

No, it's general design advice. Don't try to solve every use-case, don't try to provide too many options. That will add complexity to the project, ask users to make pointless decisions, and potentially introduce bugs in little-used features.

In this case, if I were to implement this, I'd add an extensible slug _builder_ so more features could be added later without breaking things (and without changing the existing `slug::slugify` function signature). However, given how _simple_ this library is, that's overkill. If you need more flexibility and/or control, you can and should just implement your own version that does _exactly_ what you need to do.

> I'm not sure where this conclusion comes from.

The fact that nobody has requested this feature (or any changes to the slug format) in all 7 years this project has existed.

> How would you implement it through secondary wrapping?

You can't. If you need that much control, this library isn't for you. This library is for people who just need to turn arbitrary text into slugs and want someone to have solved the problem for them already. It's not for anyone that needs fine control over _how_ that's done.

**Pull request closed without merging**
